### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by pdurbin** [craigtutterow/sna-js#4]
Is there a way to download my data from LinkedIn in a format (JSON, I assume) that would allow me to run sna-js against it while I'm offline?

I'd love to have point in time snapshots of my data and a tool such as sna-js to explore it offline at my leisure.

**Comment by webmaven** [comment]
Is this still an active issue?

**Comment by pdurbin** [comment]
@webmaven yes, I'm still actively interested in an offline mode. Thanks for checking in.

**Comment by craigtutterow** [comment]
Sorry for the delayed response on this. I used to have a download feature that exported a Pajek edgelist or csv adjacency matrix, but removed it to comply with the API terms (can't store or allow users to export data). So that makes it tough to do anything longitudinal.

**Comment by craigtutterow** [comment]
One possible solution would be to develop a Chrome extension or mobile app that caches the relevant data locally (but otherwise remains contained in the UI). This would require a lot of time, and some consideration of what the relevant features are.

**Comment by webmaven** [comment]
Any progress?

**Comment by craigtutterow** [comment]
No progress to report yet. I should have more time for development starting in May 2017 (when my postdoc ends). I hope to open source more of the code by then as well.

**Comment by pdurbin** [comment]
@craigtutterow great! I'm happy to beta test for you! Please keep me posted!

**Comment by pdurbin** [comment]
@craigtutterow hi! May is over so I thought I'd check in. I hope your postdoc went well!

**Comment by pdurbin** [comment]
@craigtutterow me again! Any news? 😄

**Comment by webmaven** [comment]
@pdurbin, it looks like @craigtutterow hasn't been active on Github at all since June 2016:

https://github.com/craigtutterow?tab=overview&from=2016-12-01&to=2016-12-31

You might try reaching out on Twitter, which he is using a bit more actively: https://twitter.com/craigtutterow

**Comment by craigtutterow** [comment]
Sorry for the delay on this. Unfortunately, I don't have much time to do further development right now. I am also not sure whether this is feasible for a third party project given the API terms. Marking this as closed for now, as I don't have an intention to work on it in the near future. If I have more time and get clarity on whether this is a permitted use, I will reopen the ticket.

**Comment by pdurbin** [comment]
Thanks for the update, @craigtutterow . Best wishes.
